import fs from "fs"
import { ArchiveRegistry, ArchiveRegistryV5, archivesRegistry, archivesRegistryV5 } from '../src/'


function genTypes(registry: ArchiveRegistry | ArchiveRegistryV5): string {
    const names: string[] = []
    for (const archive of registry.archives) { 
        names.push(`"${archive.network}"`)
    }

    return names.join("|")
}

fs.writeFileSync(`${__dirname}/../src/chains.ts`, 
`
//
// This file is a autogenerated, DO NOT EDIT. 
// Run npm run gen-types to generate this file from archives.
//

export type KnownArchives = ${genTypes(archivesRegistry)}
export type KnownArchivesV5 = ${genTypes(archivesRegistryV5)}

`
)
