import fs from "fs"
import { ArchiveRegistrySubstrate, ArchiveRegistryEVM, archivesRegistrySubstrate, archivesRegistryEVM } from '../src/'


function genTypes(registry: ArchiveRegistrySubstrate | ArchiveRegistryEVM): string {
    const names: string[] = []
    for (const archive of registry.archives) { 
        names.push(`"${archive.network}"`)
    }

    return names.join("|")
}

fs.writeFileSync(`${__dirname}/../src/chains.ts`, 
`
//
// This file is a autogenerated, DO NOT EDIT. 
// Run npm run gen-types to generate this file from archives.
//

export type KnownArchivesSubstrate = ${genTypes(archivesRegistrySubstrate)}
export type KnownArchivesEVM = ${genTypes(archivesRegistryEVM)}
export type KnownArchives = KnownArchivesSubstrate | KnownArchivesEVM

`
)
