
//
// This file is a autogenerated, DO NOT EDIT. 
// Run npm run gen-types to generate this file from archives.
//

export type KnownArchivesSubstrate = "acala" | "aleph-zero-testnet" | "amplitude" | "astar" | "bajun" | "bifrost" | "calamari" | "centrifuge" | "collectives" | "crust" | "efinity" | "elysium" | "elysium-testnet" | "equilibrium" | "frequency" | "frequency-testnet" | "gear-testnet" | "gemini-2a-testnet" | "gmordie" | "hydradx" | "integritee-network" | "interlay" | "invarch-tinkernet" | "joystream" | "karura" | "khala" | "kilt" | "kintsugi" | "kusama" | "litentry" | "litmus" | "moonbase" | "moonbeam" | "moonriver" | "opal" | "peaq" | "pendulum" | "phala" | "polkadot" | "quartz" | "reef" | "reef-testnet" | "robonomics" | "rococo" | "shibuya" | "shiden" | "snow" | "statemine" | "statemint" | "subsocial-parachain" | "subsocial" | "tanganika" | "t0rn" | "unique" | "vara" | "xx-network";
export type KnownArchivesEVM = "arbitrum" | "arbitrum-nova" | "avalanche" | "binance" | "binance-testnet" | "boba-eth" | "boba-moonbeam" | "eth-mainnet" | "exosama" | "fantom" | "goerli" | "mantle-testnet" | "moonbase" | "moonbeam" | "moonriver" | "polygon" | "polygon-mumbai" | "skale-calypso" | "skale-calypso-staging" | "skale-nebula" | "skale-nebula-staging";
export type KnownArchives = KnownArchivesSubstrate | KnownArchivesEVM;

