
//
// This file is a autogenerated, DO NOT EDIT. 
// Run npm run gen-types to generate this file from archives.
//

export type KnownArchives = "equilibrium"|"moonbeam"|"acala"|"kusama"|"polkadot"|"karura"|"crust"|"bifrost"|"moonriver"|"astar"|"shibuya"|"hydradx-snakenet"|"hydradx"|"subsocial-solochain"|"quartz"|"moonbase"|"phala"|"aleph-zero-testnet"
export type KnownArchivesV5 = "basilisk-test"|"peaq"|"calamari"|"parallel"|"moonbeam"|"clover"|"acala"|"kusama"|"polkadot"|"karura"|"crust"|"moonriver"|"astar"|"hydradx"|"subsocial"

